channels:
  - conda-forge
dependencies:
  - bokeh
  - jupyterlab
  - jupyterlab-git
  - jupyter-server-proxy
  - matplotlib
  - ipympl
  - pre-commit
  - scipy
  - panel
  - pip
  - python=3.10
  - resampy
  - pip:
    - git+https://github.com/holoviz/jupyter-panel-proxy@c22a7bdc2a69345b74550cac2b7d9220cb6a13a0
    - hapiclient
    - pyrubberband
    - git+https://github.com/Swarm-DISC/SwarmX@ac89c5c07a8130ce0083171f552ef5f53f6b5956
